# application.yml (ajustado)
spring:
  datasource:
    url: jdbc:postgresql://dpg-d4ejocmuk2gs739jbjm0-a.oregon-postgres.render.com:5432/elitedriver_9bpe
    username: elitedriver_user
    password: z95xgpelpuAWxpZnEgVjQF4imkR2WlwM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.elitedriverbackend.services.VehicleService: DEBUG

jwt:
  secret: "2dc4d72e-b851-4844-aa5d-f944e452f0d4"
  exptime: 1296000000

wompi:
    public-key: pk_test_xxxxxxxxx
    private-key: sk_test_xxxxxxxxx
    webhook-secret: whsec_xxxxxxxxx
    api-base: https://sandbox.wompi.co/v1
    reservation-expiration-minutes: 15
